- op: replace
  path: /spec/replicas
  value: 3
  target:
    kind: Deployment
    name: api-gateway
- op: replace
  path: /spec/replicas
  value: 5
  target:
    kind: Deployment
    name: scanner-service
- op: replace
  path: /spec/replicas
  value: 3
  target:
    kind: Deployment
    name: policy-engine-service
- op: replace
  path: /spec/replicas
  value: 3
  target:
    kind: Deployment
    name: notification-service
- op: replace
  path: /spec/replicas
  value: 2
  target:
    kind: Deployment
    name: billing-service
- op: replace
  path: /spec/replicas
  value: 2
  target:
    kind: Deployment
    name: report-service
- op: replace
  path: /spec/replicas
  value: 3
  target:
    kind: Deployment
    name: frontend
